project:
  target: dev-password
  outputs:
    dev-sso-browser:
      account: "{{ env_var('SNOWFLAKE_ACCOUNT') }}"
      authenticator: externalbrowser
      database: "{{ env_var('SNOWFLAKE_DATABASE') }}"
      role: "{{ env_var('SNOWFLAKE_ROLE') }}"
      schema: "{{ env_var('SNOWFLAKE_SCHEMA') }}"
      threads: 4
      type: snowflake
      user: "{{ env_var('SNOWFLAKE_USER') }}"
      warehouse: "{{ env_var('SNOWFLAKE_WAREHOUSE') }}"
    
    dev-password:
      account: "{{ env_var('SNOWFLAKE_ACCOUNT') }}"
      database: "{{ env_var('SNOWFLAKE_DATABASE') }}"
      role: "{{ env_var('SNOWFLAKE_ROLE') }}"
      schema: "{{ env_var('SNOWFLAKE_SCHEMA') }}"
      threads: 4
      type: snowflake
      user: "{{ env_var('SNOWFLAKE_NATIVE_USER') }}"
      password: "{{ env_var('SNOWFLAKE_NATIVE_PASSWORD') }}"
      warehouse: "{{ env_var('SNOWFLAKE_WAREHOUSE') }}"
    
    dev-oauth:
      account: "{{ env_var('SNOWFLAKE_ACCOUNT') }}"
      database: "{{ env_var('SNOWFLAKE_DATABASE') }}"
      role: "{{ env_var('SNOWFLAKE_ROLE') }}"
      schema: "{{ env_var('SNOWFLAKE_SCHEMA') }}"
      threads: 4
      type: snowflake
      authenticator: oauth
      user: "{{ env_var('SNOWFLAKE_OAUTH_USER') }}"
      token: "{{ env_var('SNOWFLAKE_TOKEN') }}"
      warehouse: "{{ env_var('SNOWFLAKE_WAREHOUSE') }}"
